import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Footer, Header } from "@/components";
import Providers from "../providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} dark:bg-neutral-800 bg-[#FAFAFA] dark:text-neutral-100`}>
        <Providers>
          <Header />
          <div className="pt-10">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
